export const GetLanguageName = (code: string) => {
  switch (code.toLowerCase()) {
    case "ace":
      return "Acehnese";
    case "af":
      return "Afrikaans";
    case "an":
      return "Aragonese";
    case "ar":
      return "Arabic";
    case "as":
      return "Assamese";
    case "ay":
      return "Aymara";
    case "az":
      return "Azerbaijani";
    case "ba":
      return "Bashkir";
    case "be":
      return "Belarusian";
    case "bg":
      return "Bulgarian";
    case "bho":
      return "Bhojpuri";
    case "bn":
      return "Bengali";
    case "br":
      return "Breton";
    case "bs":
      return "Bosnian";
    case "ca":
      return "Catalan";
    case "ceb":
      return "Cebuano";
    case "ckb":
      return "Kurdish (Sorani)";
    case "cs":
      return "Czech";
    case "cy":
      return "Welsh";
    case "da":
      return "Danish";
    case "de":
      return "German";
    case "el":
      return "Greek";
    case "en":
      return "English";
    case "eo":
      return "Esperanto";
    case "es":
      return "Spanish";
    case "et":
      return "Estonian";
    case "eu":
      return "Basque";
    case "fa":
      return "Persian";
    case "fi":
      return "Finnish";
    case "fr":
      return "French";
    case "ga":
      return "Irish";
    case "gl":
      return "Galician";
    case "gn":
      return "Guarani";
    case "gom":
      return "Konkani";
    case "gu":
      return "Gujarati";
    case "ha":
      return "Hausa";
    case "he":
      return "Hebrew";
    case "hi":
      return "Hindi";
    case "hr":
      return "Croatian";
    case "ht":
      return "Haitian Creole";
    case "hu":
      return "Hungarian";
    case "hy":
      return "Armenian";
    case "id":
      return "Indonesian";
    case "ig":
      return "Igbo";
    case "is":
      return "Icelandic";
    case "it":
      return "Italian";
    case "ja":
      return "Japanese";
    case "jv":
      return "Javanese";
    case "ka":
      return "Georgian";
    case "kk":
      return "Kazakh";
    case "kmr":
      return "Kurdish (Kurmanji)";
    case "ko":
      return "Korean";
    case "ky":
      return "Kyrgyz";
    case "la":
      return "Latin";
    case "lb":
      return "Luxembourgish";
    case "lmo":
      return "Lombard";
    case "ln":
      return "Lingala";
    case "lt":
      return "Lithuanian";
    case "lv":
      return "Latvian";
    case "mai":
      return "Maithili";
    case "mg":
      return "Malagasy";
    case "mi":
      return "Maori";
    case "mk":
      return "Macedonian";
    case "ml":
      return "Malayalam";
    case "mn":
      return "Mongolian";
    case "mr":
      return "Marathi";
    case "ms":
      return "Malay";
    case "mt":
      return "Maltese";
    case "my":
      return "Burmese";
    case "nb":
      return "Norwegian Bokmål";
    case "ne":
      return "Nepali";
    case "nl":
      return "Dutch";
    case "oc":
      return "Occitan";
    case "om":
      return "Oromo";
    case "pa":
      return "Punjabi";
    case "pag":
      return "Pangasinan";
    case "pam":
      return "Kapampangan";
    case "pl":
      return "Polish";
    case "prs":
      return "Dari";
    case "ps":
      return "Pashto";
    case "pt-pt":
      return "Portuguese";
    case "pt-br":
      return "Portuguese (Brazilian)";
    case "qu":
      return "Quechua";
    case "ro":
      return "Romanian";
    case "ru":
      return "Russian";
    case "sa":
      return "Sanskrit";
    case "scn":
      return "Sicilian";
    case "sk":
      return "Slovak";
    case "sl":
      return "Slovenian";
    case "sq":
      return "Albanian";
    case "sr":
      return "Serbian";
    case "st":
      return "Sesotho";
    case "su":
      return "Sundanese";
    case "sv":
      return "Swedish";
    case "sw":
      return "Swahili";
    case "ta":
      return "Tamil";
    case "te":
      return "Telugu";
    case "tg":
      return "Tajik";
    case "th":
      return "Thai";
    case "tk":
      return "Turkmen";
    case "tl":
      return "Tagalog";
    case "tn":
      return "Tswana";
    case "tr":
      return "Turkish";
    case "ts":
      return "Tsonga";
    case "tt":
      return "Tatar";
    case "uk":
      return "Ukrainian";
    case "ur":
      return "Urdu";
    case "uz":
      return "Uzbek";
    case "vi":
      return "Vietnamese";
    case "wo":
      return "Wolof";
    case "xh":
      return "Xhosa";
    case "yi":
      return "Yiddish";
    case "yue":
      return "Cantonese";
    case "zh-hans":
      return "Chinese (simplified)";
    case "zh-hant":
      return "Chinese (traditional)";
    case "zu":
      return "Zulu";
    default:
      return code;
  }
};
